channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.12
  - pytest=7.4.0
  - pandas=2.0.3
  - pytorch=2.0
  - pytorch-cuda=11.7
  # - cpuonly=2.0
  - gcc=13.1.0
  - torchvision=0.15.2
  - scikit-learn=1.3.0
  - pip:
    # cleaner scripts than using argparse
    - func-to-script==0.1.0
    # minimum mlflow packages required for logging in AzureML
    - azureml-mlflow==1.53.0
    - mlflow-skinny==2.6.0
    - pytorch-accelerated==0.1.47
